version: 0.2
phases:
install:
runtime-versions:
docker: 18
java: corretto11
pre_build:
commands:
- echo Logging in to Amazon ECR...
- aws --version
- $(aws ecr get-login --region us-east-1 --no-include-email)

- TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
- IMAGE_URI=<156962844638.dkr.ecr.us-east-1.amazonaws.com/fse-pms-auth-repo:latest>:${TAG}
build:
commands:
- echo Build started on `date`
- echo Building Java
- mvn clean
- echo Building the docker image..
- docker tag pms-auth-rep:latest 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-auth-rep:latest
post_build:
commands:
- echo Build completed on `date`
- echo Pushing docker image
- docker push $IMAGE_URI
- echo Writting definition file
- printf '[{"name":"%s","imageUri":"%s"}]' 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-auth-rep:latest> imagedefinitions.json
artifacts:
files:
- Authorization-Microservice/imagedefinitions.json
